apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tag: {{ .Values.image.tag }}
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
      tag: {{ .Values.image.tag }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        tag: {{ .Values.image.tag }}
    spec:
      containers:
      - image: nginx:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: nginx-alpine
        resources:
{{ toYaml .Values.resources | indent 12 }}
